  language: android
  jdk: oraclejdk8
    ​
  env:
    global:
      - ANDROID_API_LEVEL=27
      - ANDROID_BUILD_TOOLS_VERSION=26.1.1
      #The BuildTools version used by your project
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - extra
    ​
  #The SDK version used to compile your project
  - android-$ANDROID_API_LEVEL
  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-x86-android-27
  - sys-img-armeabi-v7a-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-license-.+'