  language: android
  jdk: oraclejdk8
    ​
  env:
    global:
      - ANDROID_API_LEVEL=25
      - ANDROID_BUILD_TOOLS_VERSION=25
      #The BuildTools version used by your project
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - extra
    ​
  #The SDK version used to compile your project
  - android-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-license-.+'
